# Generated by Django 4.2.7 on 2026-03-31 03:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('resume_text', models.TextField()),
                ('job_description', models.TextField()),
                ('match_score', models.IntegerField(default=0)),
                ('ats_score', models.IntegerField(default=0)),
                ('missing_keywords', models.JSONField(default=list)),
                ('found_keywords', models.JSONField(default=list)),
                ('section_scores', models.JSONField(default=dict)),
                ('feedback', models.JSONField(default=dict)),
                ('weak_bullets', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RewriteSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_text', models.TextField()),
                ('rewritten_text', models.TextField()),
                ('section', models.CharField(default='experience', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewrites', to='analyzer.resumeanalysis')),
            ],
        ),
    ]
