# Generated by Django 4.2.7 on 2026-04-10 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumeanalysis',
            name='resume_file',
        ),
    ]
